from __future__ import annotations

import re


TEAM_NAME_ALIASES: dict[str, dict[str, str]] = {
    "premier_league": {
        "arsenal": "Arsenal",
        "aston villa": "Aston Villa",
        "bournemouth": "Bournemouth",
        "brentford": "Brentford",
        "brighton & hove albion": "Brighton",
        "brighton": "Brighton",
        "burnley": "Burnley",
        "chelsea": "Chelsea",
        "crystal palace": "Crystal Palace",
        "everton": "Everton",
        "fulham": "Fulham",
        "leeds united": "Leeds",
        "leeds": "Leeds",
        "liverpool": "Liverpool",
        "manchester city": "Man City",
        "man city": "Man City",
        "manchester united": "Man United",
        "man united": "Man United",
        "newcastle united": "Newcastle",
        "newcastle": "Newcastle",
        "nottingham forest": "Nott'm Forest",
        "nottm forest": "Nott'm Forest",
        "sunderland": "Sunderland",
        "tottenham hotspur": "Tottenham",
        "tottenham": "Tottenham",
        "west ham united": "West Ham",
        "west ham": "West Ham",
        "wolverhampton wanderers": "Wolves",
        "wolves": "Wolves",
    },
    "la_liga": {
        "alaves": "Alaves",
        "athletic club": "Ath Bilbao",
        "athletic bilbao": "Ath Bilbao",
        "atletico madrid": "Ath Madrid",
        "barcelona": "Barcelona",
        "celta vigo": "Celta",
        "celta de vigo": "Celta",
        "celta": "Celta",
        "elche": "Elche",
        "espanyol": "Espanol",
        "getafe": "Getafe",
        "girona": "Girona",
        "levante": "Levante",
        "mallorca": "Mallorca",
        "osasuna": "Osasuna",
        "oviedo": "Oviedo",
        "rayo vallecano": "Vallecano",
        "real betis": "Betis",
        "betis": "Betis",
        "real madrid": "Real Madrid",
        "real sociedad": "Sociedad",
        "sociedad": "Sociedad",
        "sevilla": "Sevilla",
        "valencia": "Valencia",
        "villarreal": "Villarreal",
    },
    "serie_a": {
        "ac milan": "Milan",
        "atalanta": "Atalanta",
        "bologna": "Bologna",
        "cagliari": "Cagliari",
        "como": "Como",
        "fiorentina": "Fiorentina",
        "genoa": "Genoa",
        "internazionale": "Inter",
        "inter milan": "Inter",
        "inter": "Inter",
        "juventus": "Juventus",
        "lazio": "Lazio",
        "lecce": "Lecce",
        "napoli": "Napoli",
        "parma": "Parma",
        "pisa": "Pisa",
        "roma": "Roma",
        "sassuolo": "Sassuolo",
        "torino": "Torino",
        "udinese": "Udinese",
        "verona": "Verona",
    },
    "bundesliga": {
        "augsburg": "Augsburg",
        "bayer leverkusen": "Leverkusen",
        "bayern munich": "Bayern Munich",
        "borussia dortmund": "Dortmund",
        "borussia m'gladbach": "M'gladbach",
        "borussia monchengladbach": "M'gladbach",
        "eintracht frankfurt": "Ein Frankfurt",
        "freiburg": "Freiburg",
        "hamburg sv": "Hamburg",
        "hamburg": "Hamburg",
        "heidenheim": "Heidenheim",
        "hoffenheim": "Hoffenheim",
        "koln": "Koln",
        "fc koln": "Koln",
        "leipzig": "Leipzig",
        "mainz": "Mainz",
        "st pauli": "St Pauli",
        "union berlin": "Union Berlin",
        "werder bremen": "Werder Bremen",
        "wolfsburg": "Wolfsburg",
        "stuttgart": "Stuttgart",
    },
    "ligue_1": {
        "angers": "Angers",
        "auxerre": "Auxerre",
        "brest": "Brest",
        "lens": "Lens",
        "lille": "Lille",
        "lorient": "Lorient",
        "lyon": "Lyon",
        "marseille": "Marseille",
        "metz": "Metz",
        "monaco": "Monaco",
        "montpellier": "Montpellier",
        "nantes": "Nantes",
        "nice": "Nice",
        "paris saint germain": "Paris SG",
        "psg": "Paris SG",
        "paris sg": "Paris SG",
        "rennes": "Rennes",
        "strasbourg": "Strasbourg",
        "toulouse": "Toulouse",
    },
}


def normalize_team_name(name: str) -> str:
    value = name.lower().strip()
    value = value.replace("'", "")
    value = value.replace("&", " and ")
    value = re.sub(r"[^a-z0-9 ]+", " ", value)
    value = re.sub(r"\s+", " ", value).strip()
    return value


def canonical_team_name(league: str, provider_name: str) -> str | None:
    normalized = normalize_team_name(provider_name)
    aliases = TEAM_NAME_ALIASES.get(league, {})
    return aliases.get(normalized)
